### ISSUE TITLE
我macos自带py3，运行时候报错怎么解

### ISSUE THREAD

**Issue by Zhoutzzz** [yon1ng/beijing_pinan_motor#3]
以下是运行时报错的信息
```
zhoutzzz@zhoutzzzdeMacBook-Pro ~/IdeaProjects/beijing_pinan_motor (main*?) $ python3 pinanManual.py 
测试预约
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3-1.26.17-py3.11.egg/urllib3/connectionpool.py", line 711, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3-1.26.17-py3.11.egg/urllib3/connectionpool.py", line 1007, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3-1.26.17-py3.11.egg/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3-1.26.17-py3.11.egg/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3-1.26.17-py3.11.egg/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests-2.25.1-py3.11.egg/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3-1.26.17-py3.11.egg/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3-1.26.17-py3.11.egg/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='newretail.pingan.com.cn', port=443): Max retries exceeded with url: /ydt/reserve/reserveOffline?time=1696670545500 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhoutzzz/IdeaProjects/beijing_pinan_motor/pinanManual.py", line 80, in <module>
    booking("2023年06月25日 星期日", "10:00", "11:00", "FE8C62EA019420BDE0533106A8C00423")
  File "/Users/zhoutzzz/IdeaProjects/beijing_pinan_motor/pinanManual.py", line 67, in booking
    res = requests.post(booking_url, headers=book_headers, json=body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests-2.25.1-py3.11.egg/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests-2.25.1-py3.11.egg/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests-2.25.1-py3.11.egg/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests-2.25.1-py3.11.egg/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests-2.25.1-py3.11.egg/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='newretail.pingan.com.cn', port=443): Max retries exceeded with url: /ydt/reserve/reserveOffline?time=1696670545500 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))
```

**Comment by yon1ng** [comment]
python版本不能大于3.9
